### PR TITLE
Add classes for field validation errors

### PR DESCRIPTION
**Pull request by expandrew**
This will add the Foundation Abide styles to the `.ng-invalid` classes so they will show up when Angular form validations fail.

tstzzupnrl

### CODE REVIEW

**Comment by expandrew** [comment]
Heads up with this one - forms on the application right now will start showing up red because there are some changes we should make on the template side to go with this change.

(Some existing forms are using Angular validators already, so adding styling to `.ng-invalid` might show some invalid states before we're ready)

**Comment by parsakamali** [comment]
Nice. Can you change $input-background-invalid to white? the red on the background color is a lot I think.

**Comment by expandrew** [comment]
@parsakamali Like this?

image

**Comment by parsakamali** [comment]
👍 #contrast

**Comment by expandrew** [comment]
Cool, it's in there. Need to hold off on merging until we have a strategy for the existing forms on the site. I'll work on that next.

**Comment by expandrew** [comment]
Fun Friday find: 

I was able to style our fake "placeholder" options in `<select>` elements via the `.ng-empty` class. We're currently hacking our selects to display a placeholder by adding an element like this:

```html
<select>
  <!-- Placeholder -->
  <option selected disabled value="">Please choose…</option>
  <!-- All other options -->
  <option value="red">Red</option>
  <option value="green">Green</option>
  <option value="blue">Blue</option>
  <!-- ... -->
</select>
```

Angular adds `.ng-empty` to form elements without values, so that means this class is on our select elements from the start on a new form since placeholders have `value=""` and `selected` attributes.

I've co-opted this class to use our regular `$input-placeholder-color` - see below:

xsxbjrgg9b

**Pull request merged**
