### PR TITLE
Parsa/product card doc

### PR DESCRIPTION
**Pull request by parsakamali**
Edits to card documentation and created three example card types to be used/treated as templates (project, search and product cards, with hover info)

qoyqdqasrg

### CODE REVIEW

**Comment by expandrew** [comment]
@parsakamali It looks like you started this branch off of the previous branch for the typeface changes

Are you looking to merge just the last two commits on this pull request?

**Comment by parsakamali** [comment]
@expandrew DOH. yes.

**Comment by expandrew** [comment]
Writing you a list of commands to fix it, one sec

**Comment by expandrew** [comment]
Try this:

```bash
git checkout master
git fetch
git reset --hard origin/master
git checkout -b "parsa/fix-branch-product-card-doc"
git cherry-pick cf75d80c549bed810d9e63a192f805970a7b9dcf
git cherry-pick 27ad7ac374826d8bb02440e90ae3ea5d6803a227
git branch rm -D parsa/product-card-doc
git branch mv parsa/fix-branch-product-card-doc parsa/product-card-doc
git push --force origin parsa/product-card-doc
```

**Pull request merged**
