### PR TITLE
Parsa/orbit

### PR DESCRIPTION
**Pull request by parsakamali**
Styled orbit/gallery and put into modal template

### CODE REVIEW

**Comment by parsakamali** [comment]
Note this janky situation:



Images that are a different ratio pull up the caption with it (which in this example is used as "download")

If we can find a solution that can keep the caption fixed at the bottom and possibly center the smaller image that would be great.

**Comment by expandrew** [comment]
Re: the janky situation you show there:

We can just add some Imgix parameters to the `` tag in our implementation in the app, effectively using Imgix to format/crop the images for us:

```html
...
<img ng-src="{{ file.large + '&fit=crop&w=200&h=200' }}" />
...
```

**Comment by yatriks** [comment]
@expandrew @parsakamali I've temporarily added a fix for the bug where Orbit carousels are hidden by default on modals ([details here](http://foundation.zurb.com/forum/posts/2001-orbit-slider-inside-reveal-modal-has-no-height)). 

@parsakamali – we should add documentation on the "Extensions" page for the basic Orbit carousel template and a note that, when in modals, we should only ever feed Orbit images that have the same height. Does that make sense?

**Comment by parsakamali** [comment]
👍

**Pull request merged**
