### PR TITLE
Darell/remove masonry styles

### PR DESCRIPTION
**Pull request by darellkoh**
PR to remove the following:
- Deprecated `.masonry` card styles
- Deprecated `masonry-grid.html` layout template

🔪 🔪 🔪

### CODE REVIEW

**Comment by maniart** [comment]
@darellkoh don't we still need these for Projects view?

**Comment by darellkoh** [comment]
@maniart I've made the Projects view responsive :P And all other views that use masonry in Angular.

**Comment by expandrew** [comment]
Niiice so we just have to coordinate this merge with the front end release to prevent any breakage on those views. 

🔪 🔪 🔪  🎉

**Comment by darellkoh** [comment]
Yep! That's right, coming up shortly

**Pull request merged**
