### PR TITLE
Parsa/homepage

### PR DESCRIPTION
**Pull request by parsakamali**
Homepage built in static HTML…ready to start looking into animation stuff. Feel free to take a look at the structure of the page here and we can strategic componentizing soon.

### CODE REVIEW

**Comment by maniart** [comment]
@parsakamali amazing! 👏 
It looks great, and I don't have much to say as far as feedback goes, except usage of semantic HTML5 tags `section` `article` `picture` etc. -- and that is not something we tend to feel strongly about here. Just a side note. 
I think the next step is to add .js and data fetching and we'll be good!
If we have extra time, we can perhaps discuss using Gatsby.js or the like so we can use React components for it. Not a priority, but nice-to-have, time permitting. Exciting! 🎉

**Comment by parsakamali** [comment]
Update here, made a number of tweaks for mobile and navigation stuff, should be in a good place for next steps!

**Comment by parsakamali** [comment]
First pass at animating the hero cards into the graphic. Uses two different versions of the cards for simplicity's sake.

**Comment by parsakamali** [comment]
@yatriks you had mentioned splitting out the styles specific to the homepage at some point. Check this [last commit](https://github.com/Architizer/design-kit/pull/137/commits/fd0c8c1d4b4c31a47b38a2df0e390734a07e9205) and see if it makes sense....I kept the ADK overrides in the <head> and only made a stylesheet for specific things. Does it make sense to have the styles in two places? 
cc: @maniart @expandrew @darellkoh

**Comment by expandrew** [comment]
I'm cleaning it up as I implement it in the application repo 👍 

I'm using the styles you wrote and I'm putting them into a `homepage.css` file that lives in the application repo for homepage-specific styles.

Let me get a little further and I can show you what I've got

**Comment by yatriks** [comment]
Looks great

**Pull request closed without merging**
