### PR TITLE
Add pills and pill groups

### PR DESCRIPTION
**Pull request by maniart**
- Open to feedback on where to add this code, and the way it's written!

screen shot 2018-02-23 at 5 36 27 pm

### CODE REVIEW

**Comment by dennymcfadden** [comment]
@maniart two design things I noticed: **(1)** the border radius looks rounder than it is on other elements. Can we use `.20972rem` which is what we use on buttons & fields? **(2)** I don't see the text defined in your code, but could we use `$black` for `.active` and `$quicksilver-500` for the default, like this: https://www.dropbox.com/s/w3xwfaf0a1p654m/Screenshot%202018-02-26%2009.41.43.png?dl=0

**Comment by expandrew** [comment]
@maniart I added some docs actually

rsfauncklt

**Comment by maniart** [comment]
@dennymcfadden I'm going to make your proposed changes in a new branch and mention you there. Will merge this in for now to test my `architizer-website` changes on staging.

**Comment by maniart** [comment]
@expandrew Thanks much for your docs update 🙏

**Pull request merged**
